FROM 192.168.6.99/devops/uptime-kuma:build-base-alpine AS build
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
ENV NODE_OPTIONS="--dns-result-order=ipv4first"
# ENV HTTP_PROXY=http://192.168.20.38:10811
# ENV HTTPS_PROXY=http://192.168.20.38:10811

COPY .npmrc .npmrc
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN env && npm --registy=http://registry.npmmirror.com ci --omit=dev
COPY . .
RUN chmod +x /app/extra/entrypoint.sh

FROM 192.168.6.99/devops/uptime-kuma:base-alpine AS release
WORKDIR /app

# Copy app files from build layer
COPY --from=build /app /app

EXPOSE 3001
VOLUME ["/app/data"]
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD node extra/healthcheck.js
ENTRYPOINT ["/usr/bin/dumb-init", "--", "extra/entrypoint.sh"]
CMD ["node", "server/server.js"]


FROM release AS nightly
RUN npm run mark-as-nightly
