FROM louislam/uptime-kuma:base-alpine AS build
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1

COPY .npmrc .npmrc
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm --registy=http://registry.npmmirror.com ci --omit=dev
COPY . .
RUN chmod +x /app/extra/entrypoint.sh

FROM louislam/uptime-kuma:base-alpine AS release
WORKDIR /app

# Copy app files from build layer
COPY --from=build /app/config /app/config
COPY --from=build /app/db /app/db
COPY --from=build /app/dist /app/dist
COPY --from=build /app/extra /app/extra
COPY --from=build /app/index.html /app/index.html
COPY --from=build /app/public /app/public
COPY --from=build /app/server /app/server

EXPOSE 3001
VOLUME ["/app/data"]
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD node extra/healthcheck.js
ENTRYPOINT ["/usr/bin/dumb-init", "--", "extra/entrypoint.sh"]
CMD ["node", "server/server.js"]


FROM release AS nightly
RUN npm run mark-as-nightly
